name: PR Check

on:
  workflow_dispatch: # 手動実行
#    inputs: # 手動実行の時などにinputsの指定ができる。実行時にパラメータを渡す
#      description: 'Deploy target environment' # 説明
#      required: true # 入力パラメータを必須（true）にするかどうか
#      default: 'staging'

jobs:
  build: # 1つ目のジョブ
    name: Run Build
    runs-on: ubuntu-latest # ジョブを実行するための実行環境（ランナー）指定
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run build
        run: echo "Running build..." # 実際には必要なスクリプトやコマンドを記述

  test: # 2つ目のジョブ
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: echo "Running tests..." # 実際には必要なスクリプトやコマンドを記述

  lint: # 3つ目のジョブ
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run lint
        run: echo "Running linter..." # 実際には必要なスクリプトやコマンドを記述

  command:
    name: Use Linux commands
    runs-on: ubuntu-latest
    steps:
      - name: Show ubuntu details
        run: lsb_release -a
      - name: Inspect files before checkout
        run: ls -la
      - name: show current directory before checkout
        run: pwd
      - name: Checkout
        uses: actions/checkout@v5
      - name: Inspect files after checkout
        run: ls -la
      - name: show current directory after checkout
        run: pwd
      - name: show all branches after checkout
        run: git branch -a
